Tun
HeikoBornholdt/netty pull request #3
Opened 2022-10-27 22:56 UTC by HeikoBornholdt

## Motivation

I want to develop a mesh VPN. Since I love netty, I would love to use it for this project. Therefore I need a [TUN](https://en.wikipedia.org/wiki/TUN/TAP)-based `Channel` implementation to process IP packets.

## Modifications

* Added native methods to `BsdSocket` and `LinuxSocket`, allowing the creation of TUN devices and setting/getting the network interface MTU on macOS and Linux.
* Implemented `KQueueTunChannel` and `EpollTunChannel`, allowing the creation of TUN-based channels using epoll and Kqueue.
* Defined and implemented `TunChannelConfig`, allowing setting/getting the network interface MTU.
* Modified `Socket` to avoid `Socket#isIPv6(fd)` call that is not supported on TUN sockets.
* Modified `AbstractEpollChannel` allowing to set `AbstractEpollChannel#local` in `EpollTunChannel#doBind` as `Native#epollCtlAdd` must be called after TUN device has been bound.
* Renamed `AbstractKQueueDatagramChannel` to `AbstractKQueueMessageChannel` because `KQueueTunChannel` implements this class but is not datagram related. As this rename may break the API, I re-added `AbstractKQueueDatagramChannel` for legacy reasons.
* Added `Tun4Packet` and `Tun6Packet` to help work with IPv4 and IPv6 packets.
* Added `TunPingDevice` example creating a TUN device that will reply to IPMC/IPv6-ICMP echo ping requests.
* Added `TunEchoDevice` example that echoes all received IP packets (e.g., suitable for performance tests) 

## Result

New feature to create TUN-based `Channel`s on macOS- and Linux-based platforms.

## Some humble benchmarks:

TODO

## Additional Nodes
If desired, I can also provide a [Wintun](https://www.wintun.net/)-based `TunChannel` for Windows in a separate PR. [I already prototyped it](https://github.com/drasyl-overlay/netty-tun), but I'm not sure if the Wintun license is compatible with netty.

2022-10-28 21:04 UTC, KevinRoebert requested changes

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Echo4Handler.java
> +        // swap source and destination addresses. Depending on the Layer 4 protocol used, this may
"Layer" must be written in lower case?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Echo6Handler.java
> +        // swap source and destination addresses. Depending on the Layer 4 protocol used, this may
"Layer" must be written in lower case?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Echo6Handler.java
> +        packet.content().setInt(INET4_SOURCE_ADDRESS, destinationAddress);
Why IPv4 here?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Echo6Handler.java
> +        packet.content().setInt(INET4_DESTINATION_ADDRESS, sourceAddress);
Why IPv4 here?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping4Handler.java
> +                System.out.println("Reply to echo ping request from " + source.getHostAddress());
remove this?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping4Handler.java
> +                System.out.println("Ignore non echo ping request from " + packet.sourceAddress().getHostAddress());
remove this?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping4Handler.java
> +            System.out.println("Ignore non ICMP packet from " + packet.sourceAddress().getHostAddress());
remove this?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping4Handler.java
> +                System.out.println("Ignore non echo ping request from " + packet.sourceAddress().getHostAddress());
free or passthrough buffer?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping4Handler.java
> +            System.out.println("Ignore non ICMP packet from " + packet.sourceAddress().getHostAddress());
free or passthrough buffer?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping6Handler.java
> +                System.out.println("Reply to echo ping request from " + source.getHostAddress());
remove?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping6Handler.java
> +                System.out.println("Ignore non echo ping request from " + packet.sourceAddress().getHostAddress());
Free or passthrough buffer? Also remove sout?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping6Handler.java
> +            System.out.println("Ignore non IPv6-ICMP packet from " + packet.sourceAddress().getHostAddress());
Free or passthrough buffer? Also remove sout?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +public class TunEchoDevice {
Class could be final

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +public class TunEchoDevice {
Adding also a private constructor?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +        if (PlatformDependent.isOsx()) {
Why not `KQueue.isAvailable()`?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +        } else if (!PlatformDependent.isWindows()) {
Why not `Epoll.isAvailable()`?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +            System.out.println("TUN device created: " + name);
remove this?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +            if (PlatformDependent.isOsx()) {
Is it OSX dependent or KQueue dependent? Maybe better `KQueue.isAvailable()`?

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunPingDevice.java
> +public class TunPingDevice {
Same review as for `TunEchoDevice`

2022-10-28 21:04 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/TunPingDevice.java
> +            System.out.println("Address and netmask assigned: " + ADDRESS.getHostAddress() + '/' + NETMASK);
Remove this?

2022-10-28 21:04 UTC, KevinRoebert commented on pom.xml
> +                  <item>
Why?

2022-10-28 21:04 UTC, KevinRoebert commented on transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollTunChannel.java
> + * {@link TunChannel} implementation that uses linux epoll Edge-Triggered Mode for maximal
lower case

2022-10-28 21:04 UTC, KevinRoebert commented on transport-native-kqueue/src/main/c/netty_kqueue_bsdsocket.c
> +    if (connect(fd, (struct sockaddr *)&address, sizeof(address)) == -1) {
Entweder überall zwischen `*` Leerzeile oder nirgendwo. Das Gleiche gilt für `&`

2022-10-28 21:04 UTC, KevinRoebert commented on transport-native-kqueue/src/main/c/netty_kqueue_bsdsocket.c
> +    if (getsockopt(fd, SYSPROTO_CONTROL, UTUN_OPT_IFNAME, sockName, (uint32_t*) &sockNameLen) == -1) {
Entweder überall zwischen `*` Leerzeile oder nirgendwo. Das Gleiche gilt für `&`

2022-10-29 16:57 UTC, HeikoBornholdt commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +public class TunEchoDevice {
why private constructor?

2022-10-29 16:57 UTC, HeikoBornholdt commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +public class TunEchoDevice {
(its final now)

2022-10-29 17:05 UTC, HeikoBornholdt commented on example/src/main/java/io/netty/example/tun/TunEchoDevice.java
> +            if (PlatformDependent.isOsx()) {
Also in diesem konkreten Fall passt das. Aber an den anderen Fällen hast du Recht

2022-11-02 19:10 UTC, KevinRoebert requested changes

2022-11-02 19:10 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Echo4Handler.java
> +class Echo4Handler extends SimpleChannelInboundHandler<Tun4Packet> {
Why is there no modifier? I've looked into other examples (e.g., echo and udt) and they have the `public` visibility on handlers.

Also, we can add the `@Sharable` annotation on handlers without a state.

2022-11-02 19:10 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Echo6Handler.java
> +class Echo6Handler extends SimpleChannelInboundHandler<Tun6Packet> {
Why is there no modifier? I've looked into other examples (e.g., echo and udt) and they have the `public` visibility on handlers.

Also, we can add the `@Sharable` annotation on handlers without a state.

2022-11-02 19:10 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping4Handler.java
> +public class Ping4Handler extends SimpleChannelInboundHandler<Tun4Packet> {
We can add the `@Sharable` annotation on handlers without a state.

2022-11-02 19:10 UTC, KevinRoebert commented on example/src/main/java/io/netty/example/tun/Ping6Handler.java
> +public class Ping6Handler extends SimpleChannelInboundHandler<Tun6Packet> {
We can add the `@Sharable` annotation on handlers without a state.

2022-11-02 19:10 UTC, KevinRoebert commented on transport-classes-epoll/src/main/java/io/netty/channel/epoll/LinuxSocket.java
> +                throw new IOException("bind(..) failed");
three dots?

2022-11-02 19:10 UTC, KevinRoebert commented on transport-classes-kqueue/src/main/java/io/netty/channel/kqueue/BsdSocket.java
> +            // TUN devices on BSD systems must be named "tunN" were only N is passed to the OS
okay, but why is then the `TUN_DEVICE_PREFIX = "utun"` when it must be `tun`?

2022-11-02 19:10 UTC, KevinRoebert commented on transport/src/test/java/io/netty/channel/socket/Tun4PacketTest.java
> +class Tun4PacketTest {
The other test classes have a `public` modifier (e.g., `ChannelInitializerTest`).

2022-11-02 19:10 UTC, KevinRoebert commented on transport/src/test/java/io/netty/channel/socket/Tun6PacketTest.java
> +class Tun6PacketTest {
The other test classes have a `public` modifier (e.g., `ChannelInitializerTest`).

2022-11-02 19:12 UTC, KevinRoebert commented
Additionally, some classes can be final, but I am not sure how they prefer this in netty. Sometimes I see them using it, and sometimes not.

2022-11-02 19:17 UTC, KevinRoebert commented
| OS | Version | Arch |
| --- | ------- | ----- |
| MacOS | Ventura 13.0  | aarch64 (Apple M1) |
| MacOS | Monterey 12.6.1  | aarch64 (Apple M1) |
| MacOS | Monterey ? | x64 |
| Ubuntu | ? | x64 |

2022-11-02 23:59 UTC, closed without merging